# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a3837de91037c87d6b08a2b687b583017d56e8c2a5118f50d7f9015bacc179bbcac7f2c9bde3be8c30e6d78e2f423a155ea76a569d4d8aef9cb79739f8de58c

test:
  secret_key_base: d503421ef1deb969f10574209b08f2c39fce5bc50f716ffbf33849677caa491d598fd023f8f86831a93c4cbefafcf37870cfe8ec4eea3eead6d6fa58fce17441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
